# Site settings
timezone: Europe/London
title: Welcome
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jastew.com" # the base hostname & protocol for your site
permalink: /:categories/:title
production: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jason Stewart"
      image: 
        src: '/downloads/post-header.gif'
        alt: 'Post Image'
        title: '512x512 mutha fackas'

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

sass:
  style: compressed

paginate: 2
paginate_path: page/:num
pagination_limit: 3
